import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT

def generate_pdf_report(
    filename: str,
    user_name: str,
    ats_score: int,
    skills: list,
    role: str,
    match_pct: int,
    missing: list,
    learning_path: list,
    roadmap_text: str,
    interview_prep: list
):
    """Generates a professional career roadmap PDF report using ReportLab."""
    try:
        doc = SimpleDocTemplate(filename, pagesize=letter,
                                rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
        story = []
        
        styles = getSampleStyleSheet()
        
        # Define Custom Color Palette
        primary_color = colors.HexColor("#4f46e5")   # Indigo
        secondary_color = colors.HexColor("#7c3aed") # Violet
        dark_neutral = colors.HexColor("#1e293b")    # Slate 800
        light_neutral = colors.HexColor("#f8fafc")   # Slate 50
        border_color = colors.HexColor("#e2e8f0")    # Slate 200
        
        # Custom Typography
        title_style = ParagraphStyle(
            'ReportTitle',
            parent=styles['Heading1'],
            fontName='Helvetica-Bold',
            fontSize=24,
            textColor=primary_color,
            alignment=TA_CENTER,
            spaceAfter=20
        )
        
        subtitle_style = ParagraphStyle(
            'ReportSubtitle',
            parent=styles['Normal'],
            fontName='Helvetica',
            fontSize=12,
            textColor=colors.HexColor("#64748b"),
            alignment=TA_CENTER,
            spaceAfter=30
        )
        
        h1_style = ParagraphStyle(
            'SectionH1',
            parent=styles['Heading2'],
            fontName='Helvetica-Bold',
            fontSize=16,
            textColor=primary_color,
            spaceBefore=15,
            spaceAfter=10
        )
        
        h2_style = ParagraphStyle(
            'SectionH2',
            parent=styles['Heading3'],
            fontName='Helvetica-Bold',
            fontSize=13,
            textColor=secondary_color,
            spaceBefore=10,
            spaceAfter=5
        )
        
        body_style = ParagraphStyle(
            'Body',
            parent=styles['BodyText'],
            fontName='Helvetica',
            fontSize=10,
            textColor=dark_neutral,
            spaceAfter=8,
            leading=14
        )
        
        bullet_style = ParagraphStyle(
            'Bullet',
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=6
        )
        
        # 1. Header Section
        story.append(Paragraph("AI CAREER DEVELOPMENT ROADMAP", title_style))
        story.append(Paragraph(f"Prepared for: <b>{user_name}</b> | Generated by Multi-Agent System", subtitle_style))
        story.append(Spacer(1, 10))
        
        # 2. Executive Summary Metrics Table
        data = [
            [
                Paragraph("<b>ATS Score</b>", body_style),
                Paragraph("<b>Target Role</b>", body_style),
                Paragraph("<b>Profile Match</b>", body_style)
            ],
            [
                Paragraph(f"<font size=16 color='#4f46e5'><b>{ats_score}/100</b></font>", body_style),
                Paragraph(f"<b>{role}</b>", body_style),
                Paragraph(f"<font size=16 color='#7c3aed'><b>{match_pct}%</b></font>", body_style)
            ]
        ]
        
        t = Table(data, colWidths=[150, 230, 150])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), light_neutral),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 1, border_color),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BACKGROUND', (0, 1), (-1, 1), colors.white),
        ]))
        story.append(t)
        story.append(Spacer(1, 20))
        
        # 3. Resume Skills & Gap Analysis
        story.append(Paragraph("Skills & Gap Analysis", h1_style))
        story.append(Paragraph(f"<b>Extracted Skills:</b> {', '.join(skills) if skills else 'None detected'}", body_style))
        story.append(Paragraph(f"<b>Missing Skills (for target profile):</b> {', '.join(missing) if missing else 'None! Perfect match'}", body_style))
        story.append(Spacer(1, 15))
        
        # 4. Learning Pathway
        story.append(Paragraph("Recommended Learning Pathway", h1_style))
        for i, step in enumerate(learning_path, 1):
            story.append(Paragraph(f"&bull; <b>Step {i}:</b> {step}", bullet_style))
        story.append(Spacer(1, 20))
        
        # 5. Career Path Roadmap
        story.append(Paragraph("Detailed Milestone Roadmap", h1_style))
        # Replace markdown lines with pdf paragraphs
        roadmap_lines = roadmap_text.split('\n')
        for line in roadmap_lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith("###") or line.startswith("##"):
                clean_text = line.replace("#", "").strip()
                story.append(Paragraph(clean_text, h2_style))
            elif line.startswith("-") or line.startswith("*"):
                clean_text = line[1:].strip()
                story.append(Paragraph(f"&bull; {clean_text}", bullet_style))
            elif re.match(r'^\d+\.', line):
                clean_text = re.sub(r'^\d+\.', "", line).strip()
                story.append(Paragraph(f"<b>{line.split('.')[0]}.</b> {clean_text}", bullet_style))
            else:
                story.append(Paragraph(line, body_style))
        
        story.append(PageBreak())
        
        # 6. Interview Preparation Questions
        story.append(Paragraph("Tailored Technical Interview Prep", h1_style))
        story.append(Paragraph("Practice answering these questions related to your missing skills:", body_style))
        story.append(Spacer(1, 10))
        
        for i, qna in enumerate(interview_prep, 1):
            q_text = qna.get("question", "")
            a_text = qna.get("answer", "")
            story.append(Paragraph(f"<b>Q{i}: {q_text}</b>", h2_style))
            story.append(Paragraph(f"<i>Answer:</i> {a_text}", body_style))
            story.append(Spacer(1, 8))
            
        doc.build(story)
        print(f"PDF report successfully written to {filename}")
        return True
    except Exception as e:
        print(f"Error generating PDF report: {e}")
        return False

# Import regex for handling markdown cleanup in fallback
import re
